# Copyright 2020 NXP Semiconductors
# SPDX-License-Identifier: BSD-3-Clause

import cv2


INFERENCE_TIME_MESSAGE = "INFERENCE TIME"

FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SIZE = 0.8
FONT_COLOR = (0, 0, 0)
FONT_THICKNESS = 2
